name: AuraSkills-Skills-Distributor
version: '1.0-SNAPSHOT'
main: com.youssup.auraSkillsSkillsDistributor.AuraSkillsSkillsDistributor
api-version: '1.21'
authors: [ Youssup ]
description: AuraSkills Addon for allowing users to distribute their skills
website: youssup.live